services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres.env
    networks:
      - bookly-backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  bookly-backend-network:
    driver: bridge

volumes:
  postgres_data:
