services:
  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    container_name: backend
    image: backend:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.backend.env
    command: /start
    networks:
      - bookly-backend-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres.env
    networks:
      - bookly-backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  bookly-backend-network:
    driver: bridge

volumes:
  postgres_data:
